//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApiServices.WServiceReporte {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WServiceReporteSoap", Namespace="http://tempuri.org/")]
    public partial class WServiceReporte : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ListadoImpresionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListadoEstadoCuentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListadoComprobanteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WServiceReporte() {
            this.Url = global::WebApiServices.Properties.Settings.Default.WebApiServices_WServiceReporte_WServiceReporte;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ListadoImpresionCompletedEventHandler ListadoImpresionCompleted;
        
        /// <remarks/>
        public event ListadoEstadoCuentaCompletedEventHandler ListadoEstadoCuentaCompleted;
        
        /// <remarks/>
        public event ListadoComprobanteCompletedEventHandler ListadoComprobanteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListadoImpresion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ListadoImpresion(ViewModalExite ObjDetalle) {
            object[] results = this.Invoke("ListadoImpresion", new object[] {
                        ObjDetalle});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListadoImpresionAsync(ViewModalExite ObjDetalle) {
            this.ListadoImpresionAsync(ObjDetalle, null);
        }
        
        /// <remarks/>
        public void ListadoImpresionAsync(ViewModalExite ObjDetalle, object userState) {
            if ((this.ListadoImpresionOperationCompleted == null)) {
                this.ListadoImpresionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListadoImpresionOperationCompleted);
            }
            this.InvokeAsync("ListadoImpresion", new object[] {
                        ObjDetalle}, this.ListadoImpresionOperationCompleted, userState);
        }
        
        private void OnListadoImpresionOperationCompleted(object arg) {
            if ((this.ListadoImpresionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListadoImpresionCompleted(this, new ListadoImpresionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListadoEstadoCuenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ListadoEstadoCuenta(ViewModalExite ObjDetalle) {
            object[] results = this.Invoke("ListadoEstadoCuenta", new object[] {
                        ObjDetalle});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListadoEstadoCuentaAsync(ViewModalExite ObjDetalle) {
            this.ListadoEstadoCuentaAsync(ObjDetalle, null);
        }
        
        /// <remarks/>
        public void ListadoEstadoCuentaAsync(ViewModalExite ObjDetalle, object userState) {
            if ((this.ListadoEstadoCuentaOperationCompleted == null)) {
                this.ListadoEstadoCuentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListadoEstadoCuentaOperationCompleted);
            }
            this.InvokeAsync("ListadoEstadoCuenta", new object[] {
                        ObjDetalle}, this.ListadoEstadoCuentaOperationCompleted, userState);
        }
        
        private void OnListadoEstadoCuentaOperationCompleted(object arg) {
            if ((this.ListadoEstadoCuentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListadoEstadoCuentaCompleted(this, new ListadoEstadoCuentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListadoComprobante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ListadoComprobante(ViewModalExite ObjDetalle) {
            object[] results = this.Invoke("ListadoComprobante", new object[] {
                        ObjDetalle});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListadoComprobanteAsync(ViewModalExite ObjDetalle) {
            this.ListadoComprobanteAsync(ObjDetalle, null);
        }
        
        /// <remarks/>
        public void ListadoComprobanteAsync(ViewModalExite ObjDetalle, object userState) {
            if ((this.ListadoComprobanteOperationCompleted == null)) {
                this.ListadoComprobanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListadoComprobanteOperationCompleted);
            }
            this.InvokeAsync("ListadoComprobante", new object[] {
                        ObjDetalle}, this.ListadoComprobanteOperationCompleted, userState);
        }
        
        private void OnListadoComprobanteOperationCompleted(object arg) {
            if ((this.ListadoComprobanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListadoComprobanteCompleted(this, new ListadoComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ViewModalExite {
        
        private bool successField;
        
        private System.Nullable<int> valorField;
        
        private string tokemField;
        
        private string mensajeField;
        
        private object dataField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string tokem {
            get {
                return this.tokemField;
            }
            set {
                this.tokemField = value;
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        public object data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ListadoImpresionCompletedEventHandler(object sender, ListadoImpresionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListadoImpresionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListadoImpresionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ListadoEstadoCuentaCompletedEventHandler(object sender, ListadoEstadoCuentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListadoEstadoCuentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListadoEstadoCuentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ListadoComprobanteCompletedEventHandler(object sender, ListadoComprobanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListadoComprobanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListadoComprobanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591